# Generated by Django 2.2.16 on 2020-11-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_evento_atividades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='cidade',
            new_name='city',
        ),
    ]
